name: Keep Link Generator Awake

on:
  schedule:
    # This runs a script every 6 hours (at minute 0, every 6th hour)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows you to also trigger it manually if wanted

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit Web URL
        run: |
          curl -s -L -o /dev/null -w "%{http_code}" https://link-generator-web-8trpk7xz4zgpg5pkpdmdsp.streamlit.app/
